version: '2'
services:
  mariadb:
    container_name: mariadb
    hostname: mariadb
    image: mariadb:latest
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=confluence
      - MYSQL_DATABASE=confluence
      - MYSQL_USER=confluence
      - MYSQL_PASSWORD=confluence
      - character-set-server=utf8
      - collation-server=utf8_bin
    ports:
      - 3306:3306
    tmpfs:
      - /var/run
    volumes:
      - /data/mysql/data:/var/lib/mysql
      - /data/mysql/conf:/etc/mysql/conf.d
  cf:
    container_name: confluence
    image: deluxe123/confluence-server:7.0.3
    # image: atlassian/confluence-server:7.0.3
    restart: always
    ports:
      - 8091:8091
      - 8090:8090
    environment:
      - "ATL_TOMCAT_SCHEME:https"
      - "ATL_TOMCAT_SECURE:true"
      - "ATL_PROXY_NAME:confluence.dlxlife.com"
      - "ATL_PROXY_PORT:443"
    volumes:
      - /data/confluence/data:/var/atlassian/application-data/confluence
      - /data/confluence/conf:/opt/atlassian/confluence/conf
    links:
      - mariadb
